### ISSUE TITLE
Sceenshot

### ISSUE THREAD

**Issue by Lenny5156** [MasterEvarior/Processing-WebCamWithFilters#2]
# Issue Report file
## Expectet behavior:
Screenshot
<br>
## Actual behavior
Nothing!!
<br>
## Steps to reproduce the behavior
Plus "+"!
<br>
## How reproducable is the issue?
100%
<br>

Thank you for the reporting

**Comment by MasterEvarior** [comment]
Gonna look into that

**Comment by MasterEvarior** [comment]
Fixed
